server:
  port: 19687
  servlet:
    context-path: /scaffold

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

mybatis-plus:
  mapper-locations: classpath:com/htnova/**/xml/*.xml
  type-aliases-package: com.htnova
  global-config:
    db-config:
      update-strategy: IGNORED  # 编辑时全字段更新
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  header: Authorization
  refreshHeader: x-token
  expiration: 14400000    # token 过期时间 4个小时
  updateExpiration: 7200000   # 2小时的时候更新一下token
