server:
  port: 19687
  servlet:
    context-path: /scaffold

spring:
  application:
    name: scaffold
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  servlet:
    multipart:
      enabled: true
      maxFileSize: 100MB
      max-request-size: 100MB
  session:
    store-type: redis
    timeout: 1H
    redis:
      flush-mode: on_save
      namespace: springboot-session

mybatis-plus:
  mapper-locations: classpath:com/htnova/**/xml/*.xml
  type-aliases-package: com.htnova
  global-config:
    db-config:
      update-strategy: IGNORED  # 编辑时全字段更新
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
