spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: jdbc:p6spy:mysql://192.168.39.36:3306/submarine?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      validationQuery: SELECT 1
      testWhileIdle: true
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password:

  redis:
    database: 5
    host: 192.168.39.36
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8

file:
  local:
    path: C:\Users\vinson\Desktop\project\java\submarine-admin-backend\src\main\resources\public\