server:
  port: 1968
  servlet:
    context-path: /submarine
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:mysql://192.168.39.36:3306/submarine?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:p6spy:mysql://192.168.39.36:3306/submarine?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password:
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
mybatis-plus:
  mapper-locations: classpath:org/javahub/submarine/**/xml/*.xml
  type-aliases-package: org.javahub.submarine
#pagehelper:
#  helperDialect: mysql
